name: Auto-Format
on: [push, workflow_dispatch]
jobs:
  format:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Format Code
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
